### ISSUE TITLE
Any success running bluetooth-autoconnect on Raspberry PI OS Lite bullseye?

### ISSUE THREAD

**Issue by rajpancha1** [jrouleau/bluetooth-autoconnect#11]
Has anyone had success with running bluetooth-autoconnect on Raspberry PI OS Lite bullseye?
On RPI3B+ Stretch it works perfectly and I'm trying to get it to run Raspberry PI OS Lite bullseye.
Appreciate any success story and guidance regarding packages versions/configuration etc. necessary to get it working on RPI4B Lite bullseye would be greatly appreciated.
Thanks,
RP

**Comment by jonrouleau** [comment]
What errors are you receiving? Are you able to connect to the device with `bluetoothctl connect <device_mac>`?

**Comment by rajpancha1** [comment]
Jon:
Thanks for your prompt reply.

I think in Raspberry PI OS Lite bullseye there is some package compatibility issues.
~/SandBox/bluetooth-autoconnect-master $ python bluetooth-autoconnect -d -v
Traceback (most recent call last):
  File "~/SandBox/bluetooth-autoconnect-master/bluetooth-autoconnect", line 8, in <module>
    import dbus
ModuleNotFoundError: No module named 'dbus'
Can't figure out how to get around.

If I run bluetoothctl and connect with the device it connects file, here is the output:
 $ uname -a
Linux MyRPI4B-Bullseye  5.15.32-v7l+ #1538 SMP Thu Mar 31 19:39:41 BST 2022 armv7l GNU/Linux

 $ bluetoothctl
Agent registered
[CHG] Controller E4:5F:01:8F:53:C9 Pairable: yes
[bluetooth]# agent on
Agent is already registered
[bluetooth]# scan on
Discovery started

[CHG] Controller E4:5F:01:8F:53:C9 Discovering: yes
[NEW] Device 5F:27:F7:78:16:3F 5F-27-F7-78-16-3F
[NEW] Device 5D:DA:A7:04:03:8C 5D-DA-A7-04-03-8C
[NEW] Device 53:B4:63:F4:AB:B2 53-B4-63-F4-AB-B2
[bluetooth]# info 64:69:4E:93:C2:19
Device 64:69:4E:93:C2:19 (public)
        Name: Medical
        Alias: Medical
        Paired: yes
        Trusted: yes
        Blocked: no
        Connected: no
        LegacyPairing: no
        UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
        UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
        UUID: Device Information        (0000180a-0000-1000-8000-00805f9b34fb)
        UUID: Vendor specific           (cdeacb80-5235-4c07-8846-93a37ee6b86d)
        UUID: Vendor specific           (f000ffc0-0451-4000-b000-000000000000)
        Modalias: bluetooth:v000Dp0000d0110
        ManufacturerData Key: 0x6964
        ManufacturerData Value:
  4e 93 c2 19                                      N...
[bluetooth]# connect 64:69:4E:93:C2:19
Attempting to connect to 64:69:4E:93:C2:19
[CHG] Device 64:69:4E:93:C2:19 Connected: yes
Connection successful
[CHG] Device 64:69:4E:93:C2:19 ServicesResolved: yes
[Medical]# info 64:69:4E:93:C2:19
Device 64:69:4E:93:C2:19 (public)
        Name: Medical
        Alias: Medical
        Paired: yes
        Trusted: yes
        Blocked: no
        Connected: yes
        LegacyPairing: no
        UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
        UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
        UUID: Device Information        (0000180a-0000-1000-8000-00805f9b34fb)
        UUID: Vendor specific           (cdeacb80-5235-4c07-8846-93a37ee6b86d)
        UUID: Vendor specific           (f000ffc0-0451-4000-b000-000000000000)
        Modalias: bluetooth:v000Dp0000d0110
        ManufacturerData Key: 0x6964
        ManufacturerData Value:
  4e 93 c2 19                                      N...
[CHG] Device 64:69:4E:93:C2:19 ServicesResolved: no
[CHG] Device 64:69:4E:93:C2:19 Connected: no
[bluetooth]# info 64:69:4E:93:C2:19
Device 64:69:4E:93:C2:19 (public)
        Name: Medical
        Alias: Medical
        Paired: yes
        Trusted: yes
        Blocked: no
        Connected: no
        LegacyPairing: no
        UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
        UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
        UUID: Device Information        (0000180a-0000-1000-8000-00805f9b34fb)
        UUID: Vendor specific           (cdeacb80-5235-4c07-8846-93a37ee6b86d)
        UUID: Vendor specific           (f000ffc0-0451-4000-b000-000000000000)
        Modalias: bluetooth:v000Dp0000d0110
        ManufacturerData Key: 0x6964
        ManufacturerData Value:
  4e 93 c2 19                                      N...
[CHG] Device 5D:DA:A7:04:03:8C RSSI: -73
[bluetooth]#

Thanks for your help.
RP

**Comment by jonrouleau** [comment]
Looks like a missing `python-dbus` dependency. The dbus package we use here is obsolete and it may or may not be packaged for that version of Raspberry Pi. I am not familiar with the Raspberry Pi package manager so I am unable to determine if that dependency exisits on that OS. If you are unable to locate the package, consider trying the version of bluetooth-autoconnect in  https://github.com/jrouleau/bluetooth-autoconnect/pull/5 that drops `python-dbus` in favour of `glib`/`pygobject`.
