### ISSUE TITLE
Device doesn't automatically reconnect if it is taken out of range

### ISSUE THREAD

**Issue by jonrouleau** [jrouleau/bluetooth-autoconnect#2]
I've been encountering an issue where my bluetooth headset (Bose QC 35 II) doesn't automatically reconnect if I walk out of range for a sufficient amount of time. The bluetooth adapter on my laptop obviously isn't power cycled so the daemon doesn't know to trigger a connection attempt. How would it? Unless the device tries to connect (which in the case of my headset, it gives up trying to reconnect after some minutes), how would bluez or the daemon possibly know that the device is back in range?

I may consider adding an option to set a probe frequency, but my assumption is that it would have a significant impact on power usage. I'm not yet certain if this can be done in a power efficient manner.

For now, as a workaround, I manually run `bluetooth-autoconnect` upon returning to my laptop.

Any ideas or knowledge on the topic are welcome

**Comment by brettyance** [comment]
No idea. I have a similar issue with my BT keyboard. The workaround I found was `bluetoothctl power off && bluetoothctl power on`; that reconnects it fine. But seeing as it's a bluetooth keyboard, that's heavily annoying.

**Comment by jonrouleau** [comment]
@yancebrett You shouldn't need to power cycle the entire adapter unless your device is getting stuck in a semi-connected state. A simple `bluetooth-autoconnect` (which can be run independently of the daemon) should probe any trusted devices and attempt to connect to them.

My approach has been to either power cycle my headset, or manually run `bluetooth-autoconnect`. I configured the bluetooth icon on my system bar to run `bluetooth-autoconnect` when clicked so that functions as an easy one-click solution for me.

I am hesitant to add a probe timer as it isn't really in line with the intent behind this package and that functionality could be easily done by a cron job (or systemd timer) running `bluetooth-autoconnect` or even just `bluetoothctl connect <DEVICE>`.

I am closing this issue as it isn't unique to my linux install either. My android phone behaves the same way and requires me to turn bluetooth off/on if my headset is taken out of range for too long too. It's unfortunate, because it's one of those things that should "just work", but I haven't found an efficient way to entirely automate it.
