### ISSUE TITLE
Debian Package

### ISSUE THREAD

**Issue by ghost** [jrouleau/bluetooth-autoconnect#7]
Is this repository compatible with Debian?

**Comment by ghost** [comment]
Never mind, I can automatically connect Bluetooth keyboards and mice to a Debian-based computer.
I was actually planning on buying a Bluetooth Anne Pro 2 keyboard.

**Comment by jonrouleau** [comment]
It's a DBus wrapper for Bluez so there's nothing inherently preventing this from working on other distros (assuming they use Bluez), but I am not aware of anyone having packaged it for Debian so you would likely need to manage your own install (manual install instructions are listed in the Readme). Various network managers or desktop environments may provide similar functionality so you may not even need it.

This package serves to fill the gap left by Bluez by attempting to connect to known devices when the Bluetooth adapter is powered on (e.g. after booting or resuming from suspend). For me, this prevents needing to power-cycle my headphones every time I open my laptop.

Your mileage may vary.
