### ISSUE TITLE
ioctl_is_connected() Can't get HIDP connection info

### ISSUE THREAD

**Issue by shungo27** [jrouleau/bluetooth-autoconnect#9]
set up bluetooth-autoconnect, bluetoothd logs the following message when the OS boots:

`bluetoothd[506]: profiles/input/device.c:ioctl_is_connected() Can't get HIDP connection info`

Raspberry PI OS 64bit Lite bullseye
Gnome 3.38
Apple wireless keyboard
Apple magic trackpad

**Comment by jonrouleau** [comment]
This script is effectively the same as runnning `bluetoothctl connect <device_mac>` for every paired+trusted device either as a oneshot with `bluetooth-autoconnect` or whenever an adapter powers on with `bluetooth-autoconnect -d`. Errors from bluez (aka, `bluetoothd`) are outside the scope of what we can support. Please check https://github.com/bluez/bluez
